# Generated by Django 6.0b1 on 2026-01-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaVTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=200)),
                ('seccion', models.CharField(max_length=100)),
                ('stock_sistema', models.IntegerField()),
                ('inventario_real', models.IntegerField()),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento_tipo', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], max_length=20)),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
