# Generated by Django 6.0b1 on 2026-01-11 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriavts',
            options={'ordering': ['-fecha_auditoria'], 'verbose_name': 'Auditoría VTS', 'verbose_name_plural': 'Auditorías VTS'},
        ),
    ]
