# Generated by Django 6.0b1 on 2026-01-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_auditoriavts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=200)),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('fecha_ajuste', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(default='Admin_VTS', max_length=100)),
            ],
            options={
                'ordering': ['-fecha_ajuste'],
            },
        ),
    ]
