# Generated by Django 6.0b1 on 2026-01-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_historialstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialstock',
            options={},
        ),
        migrations.RemoveField(
            model_name='auditoriavts',
            name='id',
        ),
        migrations.AddField(
            model_name='auditoriavts',
            name='variante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='inventario_real',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='sku',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
