# Generated by Django 6.0b1 on 2026-01-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_historialstock_options_remove_auditoriavts_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriavts',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='documento_tipo',
            field=models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='stock_sistema',
            field=models.IntegerField(default=0),
        ),
    ]
