# Generated by Django 6.0b1 on 2026-01-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auditoriavts_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriavts',
            name='aporte_hogar_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='sku',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditoriavts',
            name='variante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Variante/Color'),
        ),
        migrations.CreateModel(
            name='LogRetirosDeducibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(default='Aporte Hogar', max_length=100)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.auditoriavts')),
            ],
        ),
    ]
