# Generated by Django 6.0b1 on 2026-01-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auditoriavts_aporte_hogar_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriavts',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del Producto'),
        ),
    ]
