# Generated by Django 6.0b1 on 2026-01-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auditoriavts_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('tipo_accion', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('operador', models.CharField(default='Sistema', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='auditoriavts',
            options={'verbose_name_plural': 'Auditorías VTS'},
        ),
    ]
