# Generated by Django 6.0b1 on 2026-01-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_registrologs_alter_auditoriavts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriavts',
            options={'ordering': ['seccion', 'producto'], 'verbose_name': 'Auditoría VTS', 'verbose_name_plural': 'Auditorías VTS'},
        ),
    ]
