# Generated by Django 6.0b1 on 2026-01-23 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_auditoriavts_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrologs',
            options={'ordering': ['-fecha_exacta']},
        ),
        migrations.RenameField(
            model_name='registrologs',
            old_name='fecha',
            new_name='fecha_exacta',
        ),
        migrations.AddField(
            model_name='registrologs',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrologs',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrologs',
            name='producto',
            field=models.CharField(max_length=255),
        ),
    ]
