# Generated by Django 6.0b1 on 2026-01-26 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_registrologs_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilVTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Boss', 'Señor de la Legión'), ('Jefe-Local', 'Cazador'), ('Analista-Bodega', 'Forjador'), ('Analista-Personal', 'Sabana (Dikbig)'), ('Analista-IT', 'Escriba (Programación)'), ('Vendedor', 'Front-Desk')], default='Vendedor', max_length=20)),
                ('sargerite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ultima_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('puede_ver_fotos', models.BooleanField(default=False)),
                ('puede_operar_stock', models.BooleanField(default=False)),
                ('puede_ver_dikbig', models.BooleanField(default=False)),
                ('puede_ejecutar_ventas', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
