# Generated by Django 6.0b1 on 2026-01-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_perfilvts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('afp', models.CharField(max_length=50)),
                ('salud', models.CharField(max_length=50)),
                ('adicional_salud', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Personal (Dikbig)',
            },
        ),
    ]
