# Generated by Django 6.0b1 on 2026-01-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
