# Generated by Django 6.0.1 on 2026-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_colaborador_comuna_colaborador_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='adicional_salud',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='salud',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='asignacion_colacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='asignacion_movilizacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='plan_isapre_uf',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Si es Isapre, ingresar valor del plan en UF. Si es Fonasa, dejar en 0.', max_digits=6),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sistema_salud',
            field=models.CharField(choices=[('FONASA', 'Fonasa 7%'), ('ISAPRE', 'Isapre (Plan UF)')], default='FONASA', max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo Fijo')], default='INDEFINIDO', help_text='Determina si aplica descuento AFC (0,6%) al trabajador.', max_length=20),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='afp',
            field=models.CharField(choices=[('CAPITAL', 'Capital'), ('CUPRUM', 'Cuprum'), ('HABITAT', 'Habitat'), ('PLANVITAL', 'PlanVital'), ('PROVIDA', 'ProVida'), ('MODELO', 'Modelo'), ('UNO', 'Uno')], default='MODELO', max_length=20),
        ),
    ]
