# Generated by Django 6.0.1 on 2026-03-09 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_colaborador_adicional_salud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteVTS',
            fields=[
                ('sku_variante', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('nombre_variante', models.CharField(max_length=100, verbose_name='Variante/Color/Fragancia')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/variantes/')),
                ('stock_sistema', models.IntegerField(default=0)),
                ('inventario_real', models.IntegerField(default=0)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('documento_tipo', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='dashboard.auditoriavts')),
            ],
            options={
                'verbose_name': 'Variante VTS',
                'verbose_name_plural': 'Variantes VTS',
                'ordering': ['producto', 'nombre_variante'],
            },
        ),
    ]
