# Generated by Django 6.0.1 on 2026-03-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_variantevts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='Parámetro')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Valor (decimal)')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración VTS',
                'verbose_name_plural': 'Configuraciones VTS',
                'ordering': ['clave'],
            },
        ),
    ]
