# Generated by Django 6.0.1 on 2026-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_configvts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialstock',
            options={'ordering': ['-fecha_ajuste']},
        ),
        migrations.AddField(
            model_name='auditoriavts',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('criocongelado', 'Criocongelado'), ('descontinuado', 'Descontinuado')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='variantevts',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('criocongelado', 'Criocongelado'), ('descontinuado', 'Descontinuado')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='plan_isapre_uf',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo Fijo')], default='INDEFINIDO', max_length=20),
        ),
    ]
