# Generated by Django 6.0.1 on 2026-03-14 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_historialstock_options_auditoriavts_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion', models.CharField(max_length=50, verbose_name='ID Transacción SumUp')),
                ('sku', models.CharField(max_length=60)),
                ('fecha_proceso', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta Registrada',
                'verbose_name_plural': 'Ventas Registradas',
                'ordering': ['-fecha_proceso'],
                'unique_together': {('id_transaccion', 'sku')},
            },
        ),
    ]
