# Generated by Django 6.0.1 on 2026-03-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_ventaregistrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_transaccion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('es_ap_hogar', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Historial de Ventas',
                'verbose_name_plural': 'Historial de Ventas',
                'ordering': ['-fecha'],
                'unique_together': {('id_transaccion', 'descripcion')},
            },
        ),
    ]
