# Generated by Django 6.0.1 on 2026-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_historialventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialventas',
            name='sku',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
