# Generated by Django 6.0.1 on 2026-07-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_historialventas_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriavts',
            name='sumup_item_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SumUp Item ID'),
        ),
    ]
